openapi: 3.0.1
info:
  title: Gestione Utenti
  version: v1
  description: Servizio per la gestione degli utenti
paths:
  /users:
    summary: Gestione utenti
    description: Api per la gestione degli utenti
    get:
      summary: Restituisce tutti gli utenti
      description: ''
      operationId: findAll
      responses:
        '200':
          description: Array of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Aggiungi utenti
      description: ''
      operationId: save
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: A single user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string