/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.0.0-beta2).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.demo.client.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-10-27T13:40:17.466+01:00[Europe/Rome]")
@Validated
@Api(value = "users", description = "the users API")
public interface UsersApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /users : Restituisce tutti gli utenti
     *
     * @return Default error sample response (status code 200)
     */
    @ApiOperation(value = "Restituisce tutti gli utenti", nickname = "findAll", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Default error sample response") })
    @GetMapping(
        value = "/users"
    )
    default ResponseEntity<Void> _findAll() {
        return findAll();
    }

    // Override this method
    default  ResponseEntity<Void> findAll() {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /users : Aggiungi utenti
     *
     * @return Default error sample response (status code 200)
     */
    @ApiOperation(value = "Aggiungi utenti", nickname = "save", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Default error sample response") })
    @PostMapping(
        value = "/users"
    )
    default ResponseEntity<Void> _save() {
        return save();
    }

    // Override this method
    default  ResponseEntity<Void> save() {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
